services:
  - name: douala-luxury-rent
    type: web
    env: node
    plan: free
    region: frankfurt   # proche de la France ; change si besoin
    buildCommand: |
      cd backend
      npm ci
    startCommand: |
      cd backend
      npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false   # tu la définiras dans Render > Environment
